#services:
#  vllm-qwen3-32b:
#    image: vllm/vllm-openai:latest
#    container_name: vllm-qwen3-32b
#    ports:
#      - "8000:8000"
#    volumes:
#      - /home/administrator/w183/huggingface_cache:/root/.cache/huggingface
#    command: >
#      --model Qwen/Qwen3-32B
#      --quantization fp8
#      --kv-cache-dtype fp8
#      --trust-remote-code
#      --host 0.0.0.0
#      --port 8000
#      --gpu-memory-utilization 0.92
#      --max-num-seqs 6
#      --enable-chunked-prefill
#      --swap-space 8
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]

services:
  vllm-qwen3-32b:
    image: vllm/vllm-openai:latest
    container_name: vllm-qwen3-32b
    ports:
      - "8000:8000"
    volumes:
      - /home/administrator/w183/huggingface_cache:/root/.cache/huggingface
    command: >
      --model Qwen/Qwen3-32B
      --quantization fp8
      --kv-cache-dtype fp8
      --trust-remote-code
      --host 0.0.0.0
      --port 8000
      --gpu-memory-utilization 0.92
      --max-num-seqs 6
      --max-model-len 32768
      --enable-chunked-prefill
      --max-num-batched-tokens 11288
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

#services:
#  vllm-qwen3-32b-awq:
#    image: vllm/vllm-openai:latest
#    container_name: vllm-qwen3-32b-awq
#    ports:
#      - "8000:8000"
#    volumes:
#      - /home/administrator/w183/huggingface_cache:/root/.cache/huggingface
#    command: >
#      --model Qwen/Qwen3-32B-AWQ
#      --quantization awq
#      --trust-remote-code
#      --host 0.0.0.0
#      --gpu-memory-utilization 0.92
#      --max-num-seqs 16
#      --max-model-len 32768
#      --enable-chunked-prefill
#      --max-num-batched-tokens 12288
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [ gpu ]